[package]
name = "PhysicsSim"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.20"
winit = "0.29"
egui = "0.28"
egui-wgpu = "0.28"
egui-winit = "0.28"
egui_plot = "0.28"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }
rand = "0.8"
env_logger = "0.11"
log = "0.4"
